from turtle import *

def circle1(csize, ccolor):
    fill = input('Fill or outline? (0 = Fill, 1 = Outline) ')
    newfill = int(fill)
    if newfill == 0:
        color(ccolor)        
        begin_fill()
        circle(csize)
        end_fill()
    else:
        color(ccolor)
        circle(csize)

    mainloop()

def pentagon1(psize, pcolor):
    fill = input('Fill or outline? (0 = Fill, 1 = Outline) ')
    newfill = int(fill)
    if newfill == 0:
        color(pcolor)
        begin_fill()
        fd(psize)
        left(72)
        forward(psize)
        left(72)
        forward(psize)
        left(72)
        forward(psize)
        left(72)
        forward(psize)
        end_fill()
    else:
        color(pcolor)
        fd(psize)
        left(72)
        forward(psize)
        left(72)
        forward(psize)
        left(72)
        forward(psize)
        left(72)
        forward(psize)

    mainloop()
def square1(ssize, scolor):
    fill = input('Fill or outline? (0 = Fill, 1 = Outline) ')
    newfill = int(fill)
    if newfill == 0:
        color(scolor)
        begin_fill()
        forward(ssize)
        left(90)
        forward(ssize)
        left(90)
        forward(ssize)
        left(90)
        forward(ssize)
        end_fill()
    else:
        color(scolor)
        forward(ssize)
        left(90)
        forward(ssize)
        left(90)
        forward(ssize)
        left(90)
        forward(ssize)

    mainloop()
def star1(stsize, stcolor):
    fill = input('Fill or outline? (0 = Fill, 1 = Outline) ')
    newfill = int(fill)
    if newfill == 0:
        color(stcolor)
        begin_fill()
        rt(72)
        fd(stsize)
        lt(72)
        fd(stsize)
        rt(144)
        fd(stsize)
        lt(72)
        fd(stsize)
        rt(144)
        fd(stsize)
        lt(72)
        fd(stsize)
        rt(144)
        fd(stsize)
        lt(72)
        fd(stsize)
        rt(144)
        fd(stsize)
        lt(72)
        fd(stsize)
        end_fill()
    else:
        color(stcolor)
        rt(72)
        fd(stsize)
        lt(72)
        fd(stsize)
        rt(144)
        fd(stsize)
        lt(72)
        fd(stsize)
        rt(144)
        fd(stsize)
        lt(72)
        fd(stsize)
        rt(144)
        fd(stsize)
        lt(72)
        fd(stsize)
        rt(144)
        fd(stsize)
        lt(72)
        fd(stsize)

    mainloop()

answer = input('Would you like a circle ("c"), square ("s"), pentagon ("p"), or star("st")? ')
newanswer = answer.lower()
size = input('How big would you like it? ')
newsize = int(size)
shapecolor = input('Shape color? ')
newcolor = shapecolor.lower()
if newanswer == 'c':
    circle1(newsize, newcolor)
elif newanswer == 's':
    square1(newsize, newcolor)
elif newanswer == 'p':
    pentagon1(newsize, newcolor)
elif newanswer == 'st':
    star1(newsize, newcolor)
else:
    print('Sorry, invalid shape.')